spring:
  application:
    name: companysearch
logging:
  level:
    com.trunarrative.companysearch: DEBUG

trunarrative-api:
  name: trunarrative-api
#  url: https://exercise.trunarrative.cloud/TruProxyAPI/rest/Companies/v1/
  url: https://httpstat.us/500